'use server';
import { revalidatePath } from 'next/cache';
import { getBusinessContext } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';

export type QuoteInput={customerId?:string|null;desiredAt?:string|null;notes?:string;deliveryFee?:number;discount?:number;items:Array<{productId:string;variantId?:string|null;name:string;quantity:number;unitPrice:number;configuration?:Record<string,unknown>}>};
export async function createQuoteAction(input:QuoteInput){const context=await getBusinessContext();if(!context)return{ok:false,error:'Confeitaria não encontrada.'};if(!input.items?.length)return{ok:false,error:'Adicione pelo menos um item.'};const supabase=await createClient();const subtotal=input.items.reduce((s,i)=>s+Number(i.quantity)*Number(i.unitPrice),0);const discount=Math.max(Number(input.discount||0),0);const deliveryFee=Math.max(Number(input.deliveryFee||0),0);const total=Math.max(subtotal-discount+deliveryFee,0);const {data:quote,error}=await supabase.from('quotes').insert({business_id:context.business.id,customer_id:input.customerId||null,status:'draft',desired_at:input.desiredAt?new Date(input.desiredAt).toISOString():null,subtotal,discount,delivery_fee:deliveryFee,total,notes:input.notes||null,expires_at:new Date(Date.now()+7*86400000).toISOString()}).select('id').single();if(error||!quote)return{ok:false,error:error?.message||'Falha ao criar orçamento.'};const {error:itemError}=await supabase.from('quote_items').insert(input.items.map(i=>({business_id:context.business.id,quote_id:quote.id,product_id:i.productId,product_variant_id:i.variantId||null,name_snapshot:i.name,quantity:i.quantity,unit_price:i.unitPrice,total_price:Number(i.quantity)*Number(i.unitPrice),configuration:i.configuration||{}})));if(itemError){await supabase.from('quotes').delete().eq('id',quote.id);return{ok:false,error:itemError.message}}revalidatePath('/painel/orcamentos');return{ok:true,quoteId:quote.id}}

export async function markQuoteSentAction(id:string){const context=await getBusinessContext();if(!context)return{ok:false};const supabase=await createClient();const{error}=await supabase.from('quotes').update({status:'sent'}).eq('business_id',context.business.id).eq('id',id);revalidatePath('/painel/orcamentos');return{ok:!error,error:error?.message}}

export async function approveQuoteAction(id:string){const context=await getBusinessContext();if(!context)return{ok:false,error:'Confeitaria não encontrada.'};const supabase=await createClient();const [{data:quote},{data:items=[]}]=await Promise.all([supabase.from('quotes').select('*').eq('business_id',context.business.id).eq('id',id).single(),supabase.from('quote_items').select('*').eq('business_id',context.business.id).eq('quote_id',id)]);if(!quote)return{ok:false,error:'Orçamento não encontrado.'};const {data:order,error}=await supabase.from('orders').insert({business_id:context.business.id,customer_id:quote.customer_id,quote_id:id,status:'awaiting_deposit',fulfillment_type:'pickup',scheduled_at:quote.desired_at,subtotal:quote.subtotal,discount:quote.discount,delivery_fee:quote.delivery_fee,total:quote.total,deposit_required:Number(quote.total)*.5,notes:quote.notes}).select('id').single();if(error||!order)return{ok:false,error:error?.message||'Falha ao converter.'};const productIds=(items??[]).map((i:any)=>i.product_id).filter(Boolean);const {data:recipes=[]}=await supabase.from('recipes').select('product_id,product_variant_id,active_version_id').eq('business_id',context.business.id).in('product_id',productIds.length?productIds:['00000000-0000-0000-0000-000000000000']).eq('is_complete',true);const versionFor=(item:any)=>{const exact=(recipes??[]).find(r=>r.product_id===item.product_id&&r.product_variant_id===item.product_variant_id);const base=(recipes??[]).find(r=>r.product_id===item.product_id&&!r.product_variant_id);return exact?.active_version_id||base?.active_version_id||null};const{error:orderItemsError}=await supabase.from('order_items').insert((items??[]).map((i:any)=>({business_id:context.business.id,order_id:order.id,product_id:i.product_id,product_variant_id:i.product_variant_id,name_snapshot:i.name_snapshot,quantity:i.quantity,unit_price:i.unit_price,total_price:i.total_price,configuration:i.configuration||{},recipe_version_id:versionFor(i)})));if(orderItemsError){await supabase.from('orders').delete().eq('id',order.id);return{ok:false,error:orderItemsError.message}}await supabase.from('quotes').update({status:'approved'}).eq('id',id);revalidatePath('/painel/orcamentos');revalidatePath('/painel/pedidos');return{ok:true,orderId:order.id}}
