import Link from 'next/link';
import { PageHeader } from '@/components/page-header';
import { getBusinessContext, hasPermission } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';
import { createInventoryItemAction } from '../actions';
import { recordLossNormalizedAction } from './actions';
import { numberPt, money } from '@/lib/format';

export default async function EstoquePage() {
  const context = await getBusinessContext(); if (!context) return null;
  const canAdjust=hasPermission(context,'adjust_stock');
  const supabase = await createClient();
  const [stockResult, itemsResult] = await Promise.all([
    supabase.from('inventory_stock_summary').select('*').eq('business_id', context.business.id).order('name'),
    supabase.from('inventory_items').select('id,name,base_unit,average_unit_cost,item_type').eq('business_id', context.business.id).eq('active', true).order('name')
  ]);
  const stock = stockResult.data ?? [];
  const items = itemsResult.data ?? [];

  return <>
    <PageHeader eyebrow="Estoque inteligente" title="Estoque" description="Físico, reservado e disponível. Compras, perdas e produção são normalizadas na unidade-base automaticamente." actionHref={canAdjust?"/painel/estoque/inventario":"/painel/compras/lista"} actionLabel={canAdjust?"Conferir estoque":"Ver lista de compras"} />
    <div className="mb-5 grid gap-3 md:grid-cols-3"><Metric label="Itens" value={String(stock.length)} /><Metric label="Abaixo do mínimo" value={String(stock.filter(s => Number(s.available) < Number(s.min_stock)).length)} attention /><Metric label="Valor estimado" value={money(stock.reduce((sum, s) => { const item = items.find(i => i.id === s.inventory_item_id); return sum + Number(s.on_hand) * Number(item?.average_unit_cost ?? 0); }, 0))} /></div>
    <section className="panel mb-5 overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-wine/10 px-5 py-3"><div className="grid flex-1 grid-cols-[1.5fr_.7fr_.7fr_.7fr] gap-2 text-[10px] font-bold uppercase tracking-wider text-graphite/40"><span>Item</span><span>Físico</span><span>Reservado</span><span>Disponível</span></div><Link href="/painel/compras/lista" className="hidden shrink-0 rounded-xl bg-cream px-3 py-2 text-[10px] font-bold text-wine lg:block">Lista de compras</Link></div>{stock.length === 0 ? <div className="p-8 text-center text-sm text-graphite/45">Nenhum ingrediente cadastrado.</div> : stock.map(s => <div key={s.inventory_item_id} className="grid grid-cols-[1.5fr_.7fr_.7fr_.7fr] items-center gap-2 border-b border-wine/5 px-5 py-4 text-xs last:border-0"><div><p className="m-0 font-bold text-graphite">{s.name}</p>{Number(s.available) < Number(s.min_stock) && <p className="m-0 mt-1 text-[10px] font-bold text-danger">Abaixo do mínimo ({numberPt(s.min_stock)} {s.base_unit})</p>}</div><span>{numberPt(s.on_hand)} {s.base_unit}</span><span className="text-terracotta">{numberPt(s.reserved)} {s.base_unit}</span><strong className="text-wine">{numberPt(s.available)} {s.base_unit}</strong></div>)}</section>
    {canAdjust?<div className="grid gap-5 lg:grid-cols-2"><form action={createInventoryItemAction} className="panel p-5"><p className="eyebrow mb-1">Cadastro</p><h2 className="mt-0 text-xl font-black text-wine">Novo ingrediente ou material</h2><div className="grid gap-3 sm:grid-cols-2"><input required name="name" placeholder="Nome" className="input sm:col-span-2" /><select name="item_type" className="input"><option value="ingredient">Ingrediente</option><option value="packaging">Embalagem</option><option value="material">Material</option><option value="intermediate">Preparado</option><option value="finished">Produto acabado</option></select><select name="base_unit" className="input"><option value="g">gramas (g)</option><option value="ml">mililitros (ml)</option><option value="un">unidade</option><option value="kg">kg</option><option value="L">litro</option></select><input name="purchase_unit" placeholder="Como compra? Ex.: pacote" className="input" /><input name="purchase_unit_multiplier" type="number" min="0.0001" step="0.0001" defaultValue="1" placeholder="Conteúdo da embalagem" className="input" /><input name="opening_qty" type="number" min="0" step="0.0001" placeholder="Estoque atual" className="input" /><input name="min_stock" type="number" min="0" step="0.0001" placeholder="Estoque mínimo" className="input" /><input name="unit_cost" type="number" min="0" step="0.000001" placeholder="Custo por unidade base" className="input sm:col-span-2" /><label className="flex items-center gap-2 text-xs text-graphite/60"><input type="checkbox" name="track_expiry" /> Controlar validade</label></div><p className="mb-0 mt-3 text-[10px] leading-4 text-graphite/40">Ex.: estoque em g, compra em pacote e 1 pacote = 2.100 g. A lista automática usa essa informação para sugerir quantos pacotes comprar.</p><button className="mt-4 h-11 w-full rounded-2xl bg-wine text-sm font-bold text-cream">Cadastrar item</button></form>
    <form action={recordLossNormalizedAction} className="panel h-fit p-5"><p className="eyebrow mb-1">Desperdício</p><h2 className="mt-0 text-xl font-black text-wine">Registrar perda</h2><div className="space-y-3"><select required name="inventory_item_id" className="input"><option value="">Selecione o item</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input required name="quantity" type="number" min="0.0001" step="0.0001" placeholder="Quantidade" className="input" /><select required name="unit" className="input"><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="L">L</option><option value="un">un</option></select></div><select name="reason" className="input"><option>Vencimento</option><option>Erro de produção</option><option>Quebra</option><option>Derramamento</option><option>Qualidade inadequada</option><option>Uso interno</option><option>Degustação</option><option>Outro</option></select></div><button className="mt-4 h-11 w-full rounded-2xl bg-terracotta text-sm font-bold text-white">Registrar perda</button></form></div>:<div className="panel p-5 text-xs leading-5 text-graphite/50">Seu perfil possui acesso de consulta ao estoque. Cadastro, perdas e conferências ficam disponíveis somente para quem tem permissão de ajuste.</div>}
  </>;
}

function Metric({ label, value, attention = false }: { label: string; value: string; attention?: boolean }) { return <div className={`panel p-5 ${attention ? 'border-terracotta/30' : ''}`}><p className="eyebrow mb-2">{label}</p><p className={`m-0 text-2xl font-black ${attention ? 'text-terracotta' : 'text-wine'}`}>{value}</p></div>; }
